config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'

  get "googled0a82c4a39ac538d.html", to: "site#googled0a82c4a39ac538d"

  get "about", to: 'site#show'
  get "resume", to: 'site#cv'

  resources :blog_posts, :path => "blog"
  get 'contact', to: 'contacts#new'
  post 'contacts', to: 'contacts#create'

  get 'download-cv', to: 'site#download'

  resources :sessions, only: [:create, :destroy]
  get '/backdoor/login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  default_scope { order('created_at DESC') }

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/contact.rb
class Contact < MailForm::Base

  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,    :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "My Contact Form",
      :to => "khanjani.fardin@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def admin?
    current_user.admin if current_user
  end
  helper_method :admin?

  def authorize
    redirect_to root_path if !admin?
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController 
  before_action :find_blog_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:index, :show]

  def index
    if params[:id]
      @blog_posts = BlogPost.where('id < ?', params[:id]).limit(2)
    else
      @blog_posts = BlogPost.first(2)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @blog_post = BlogPost.new
  end

  def show
  end

  def create
    @blog_post = BlogPost.create(blog_post_params)
    @blog_post.photo = params[:photo]

    if @blog_post.save
      flash[:notice] = "Post created!"
      redirect_to blog_posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @blog_post.update_attributes(blog_post_params)
      flash[:notice] = "Post updated!"
      redirect_to @blog_post
    else
      render 'edit'
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to blog_posts_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :body, :photo)
  end

  def find_blog_post
    @blog_post = BlogPost.friendly.find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    
    if @contact.deliver
      flash.now[:alert] = nil
      flash[:contact] = "Thank you for your message! I'll get back to you shortly."
      redirect_to contact_path
    else
      flash.now[:alert] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice]= "Logged in!"
      redirect_to root_path
    else 
      flash.now.alert = "Email or passowrd invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
    flash[:notice]=  "Logged out"
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    if params[:id]
      @blog_posts = BlogPost.where('id < ?', params[:id]).limit(2)
    else
      @blog_posts = BlogPost.first(2)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  end

  def contact
  end

  def cv
  end

  def googled0a82c4a39ac538d
    render layout: false
  end

  def download
    file = "#{Rails.root}/fardin_khanjani_cv.pdf"
    if File.exists?(file)
      send_file file, :type=>"application/pdf", :x_sendfile=>true
    else
      flash[:notice] = 'File not found'
      redirect_to :index
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/blog_posts/_blog_post.html.erb
<div class="col-sm-6">
  <div class="panel panel-default" data-id="<%= blog_post.id %>">
    <%= link_to(blog_post)  do %>
      <div class="panel-thumbnail">
        <%= image_tag("#{blog_post.photo}") %>
        <p><%= blog_post.title %></p>
      </div>
      <div class="panel-body">
        <%= truncate(blog_post.body, length: 120) %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/blog_posts/_form.html.erb
<div class="container profile">
  <%= form_for @blog_post do |f| %>

  <fieldset class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.file_field :photo, class: "form-control" %>
  </fieldset>

    <%= f.submit  class: 'btn btn-secondary' %>

  <% end %>
</div>

app/views/blog_posts/edit.html.erb
<%= render 'form'%>

app/views/blog_posts/index.html.erb
<% title "Blog" %>

<section id="blog-header" class="has-bg-pic">
  <div class="pg-title">
      <h3>My thoughts and</h3>
      <h1>BLOG POSTS</h1>
  </div>
</section>

<section id="blog-gallery" class="auto-height text-center">
  <% if admin? %>
      <button class="centered"><%= link_to "New Post", new_blog_post_path %></button>
    <% end %>
  <div class="row">
    <%= render @blog_posts %>
  </div>

  <%= javascript_tag do %>
    window.post_count = <%= BlogPost.all.count %>
  <% end %>

  <div class="load-more-div">
    <%= image_tag "ajax-loader.gif", style: "display:none;", class: "loading-gif" %>
    <%= link_to "Older posts", blog_posts_path, class: "load-more" %>
  </div>
</section>

app/views/blog_posts/index.js.erb
$('.row').append('<%= escape_javascript(render(:partial => @blog_posts)) %>')

app/views/blog_posts/new.html.erb
<%= render 'form'%>

app/views/blog_posts/show.html.erb
<% title "#{@blog_post.title}" %>

<section id="blog-post" class="has-bg-pic" style='background-image: url(<%= @blog_post.photo_url %>)'>
  <div class="pg-title">
    <h1><%= @blog_post.title %></h1>
  </div>
</section>

<section id="blog-post-body" class="auto-height">
  <div class="blog-post-body">
    <%= simple_format(@blog_post.body) %>
  </div>
</section>

<% if admin? %>
  <button>
    <%= link_to "Edit this post", edit_blog_post_path(@blog_post) %>
  </button>
  <button>
    <%= link_to "Delete this post", blog_post_path, method: :delete %>
  </button>
<% end %>

app/views/contacts/new.html.erb
<% title "Contact me" %>

<section id="contact-header" class="has-bg-pic">
  <div class="pg-title">
    <% if flash[:contact] %> 
      <p class="notice"><%= flash[:contact] %></p>
    <% else %>
      <h3>Say</h3>
      <h1>HELLO</h1>
    <% end %>
  </div>
</section>


<section id="contact-form" class="auto-height">
  <div class="container">
    <div class="col-sm-6 contact-data">
      <h4>CONTACT INFORMATION</h4>
      <p>Fardin Khanjani</p>
      <p>Budapest, Hungary</p>
      <p>+36 70 466 1931</p>
      <p>khanjani.fardin@gmail.com</p>
    </div>

    <div class="col-sm-6">
      <%= form_for @contact do |f| %>
        <fieldset class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </fieldset>

        <fieldset class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
        </fieldset>

        <fieldset class="form-group">
          <%= f.label :message %>
          <%= f.text_area :message, class: "form-control" %>
        </fieldset>

        <%= f.submit "Send", class: "submit-btn"%>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= display_meta_tags site: 'Fardin Khanjani' %>

    <%= stylesheet_link_tag    'animsition.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
    

  </head>
  <body>
    <%= render 'shared/navbar' %> <!-- it's out of the container cuz it should not be affected by animsition transition -->
    <div class="container-fluid animsition">
      <%= yield %>
      <div class="footer"> <%= render 'shared/footer' %></div>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
  <a href="https://bitbucket.org/fardin01/" target="_blank"><i class="fa fa-bitbucket footer-social-btn"></i></a>
   <a href="https://github.com/fardin01/" target="_blank"><i class="fa fa-github footer-social-btn"></i></a>
  <a href="https://hu.linkedin.com/in/fardin-khanjani-9960b817" target="_blank"><i class="fa fa-linkedin footer-social-btn"></i></a>
  <a href="mailto:khanjani.fardin@gmail.com" target="_top"><i class="fa fa-envelope-o footer-social-btn"></i></a>


 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74617920-1', 'www.fardinkhanjani.com');
  ga('send', 'pageview');
</script>


<%= javascript_include_tag 'animsition.min.js' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'FARDIN KHANJANI', root_path, class: 'navbar-brand logo animsition-link' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path, class: 'nav-link animsition-link' %></li>
        <li><%= link_to "Blog", blog_posts_path, class: 'nav-link animsition-link'%></li>
        <li><%= link_to "Resume/CV", resume_path, class: 'nav-link animsition-link' %></li>
        <li><%= link_to "Contact", contact_path, class: 'nav-link animsition-link' %></li>
        <% if admin? %>
          <li class="nav-item"><%= link_to "Log out", logout_path, class: 'nav-link animsition-link' %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/site/cv.html.erb
<% title "CV/Resume" %>

<section id="cv-header" class="has-bg-pic">
  <div class="pg-title">
      <h3>What I've done and</h3>
      <h1>MY HISTORY SO FAR</h1>
  </div>
</section>

<section id="cv" class="auto-height">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 works">
        <div class="col-sm-4">
         <h2>WORK EXPERIENCE</h2>
        </div>

        <div class="col-sm-8">
          <div class="cv-item">
            <h5>Cogniso Ltd</h5>
            <strong>June 2015 – March 2016, Budapest Hungary</strong>
            <p class="cv-desc">
              Junior Rails developer, Market Research and Social networks
            </p>
          </div>

          <div class="cv-item">
            <h5>Win TV Live Satellite Channel</h5>
            <strong>September 2014 - Present, Budapest Hungary</strong>

              <p class="cv-desc">Game show host: Performing live shows, answering phone calls of participants, promoting the show and explaining the process. </p>
              <p class="cv-desc">Game show editor/control room: Editing the content and foreseeing the overall status of the show</p> 

          </div>

          <div class="cv-item">
            <h5>Avesta Sole Trading</h5>
            <strong>April 2014- April 2015, Budapest Hungary</strong>
              <p class="cv-desc">Self-employed: International commodity trading</p>
          </div>

          <div class="cv-item">
            <h5>The Bay Company</h5>
            <strong>May-September 2012 San Francisco USA</strong>
              <p class="cv-desc">Full time employee (intern): Customer orientation, customer relation/assistance, cash register, warehouse and restocking, closing and recovering the store
            </p>
          </div>

          <div class="cv-item">
            <h5>Sanam Home Appliances</h5>
            <strong>Summers 2006-07-08 Hamedan Iran</strong>
              <p class="cv-desc">General employee: Customer service, Customer orientation and sales, packaging and restocking items, receiving and stocking merchandise in warehouse, inventory, assisting with B2B transactions
            </p>
          </div>
        </div><!-- col-sm-8 -->
      </div><!-- col-sm-12 works -->

      <div class="col-sm-12 studies">
        <div class="col-sm-4 ">
         <h2>Education</h2>
        </div>

        <div class="col-sm-8">
          <div class="cv-item">
            <h5>International Business School / Oxford Brookes University</h5>
            <strong>Budapest Hungary, 2012 – Present</strong>
              <p class="cv-desc">Bachelor of Arts in Business Studies</p>
          </div>

          <div class="cv-item">
            <h5>McDaniel College</h5>
            <strong>Budapest Hungary, 2010 - 2012</strong>
              <p class="cv-desc">Business Administration and Economics</p> 
          </div>

          <div class="cv-item">
            <h5>Avicenna International College</h5>
            <strong>Budapest Hungary, 2009 - 2010</strong>
              <p class="cv-desc">International high school diploma</p> 
          </div>

          <div class="cv-item">
            <h5>Darolfonon High School</h5>
            <strong>Hamedan Iran, 2007 - 2009</strong>
              <p class="cv-desc">Mathematics major</p> 
          </div>
        </div><!-- col-sm-9 -->
      </div><!-- col-sm-12 studies -->
    </div><!-- row -->
  </div>
  <%= link_to "Download full resume", download_cv_path, class: 'cv-dl-btn' %>
</section>

app/views/site/googled0a82c4a39ac538d.html.erb
google-site-verification: googled0a82c4a39ac538d.html

app/views/site/index.html.erb
<% title "Home" %>

<section id="intro" class="has-bg-pic">
  <h1>Hey. My name is Fardin. You can call me Freddie</h1>
  <div class="intro">
      <%= link_to "My story",about_path, class:"intro-btn" %>
      <%= link_to "My resume",resume_path, class:"intro-btn" %>
  </div>
</section>

<section id="nutshell" class="auto-height">
  <div>
    <h1>In a nutshell</h1>
    <p>I have a passion for coding and learning new things. At the moment I am learning two new languages, Hungarian and Swedish, I'm practicing coding and studying at university at the same time</p>
  </div>
</section>

<section id="blog-gallery" class="auto-height text-center">
  <h1>Blog posts</h1>
  <div class="row">
    <%= render @blog_posts %>
  </div>

  <%= javascript_tag do %>
    window.post_count = <%= BlogPost.all.count %>
  <% end %>

  <div class="load-more-div">
    <%= image_tag "ajax-loader.gif", style: "display:none;", class: "loading-gif" %>
    <%= link_to "Older posts", blog_posts_path, class: "load-more" %>
  </div>
</section>

<section id="say-hello" class="auto-height text-center">
  <%= link_to "Something interesting? Say hello!", contact_path, class:"say-hello-btn" %>
</section>

app/views/site/show.html.erb
<% title "About me" %>


<section id="about-header" class="has-bg-pic">
  <div class="pg-title">
      <h3>Read about me and</h3>
      <h1>MY JOURNEY SO FAR</h1>
  </div>
</section>

<section id="about-text" class="auto-height">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <div class="about-text">
        <p>I'm a 24 year old energetic cheerful last year student who loves to discuss ideas and turn them into reality. I've been living in Europe for over 8 years and have done various jobs from Market research to managing rental apartments to hosting live TV shows.</p>

        <p>After I heard about coding and web apps I grew a passion for writing code and creating useful apps. That's how this website came into life as my very first project. Ruby on Rails is my weapon of choice and Javascript is on the way.</p>

        <p>My university major however is Business Studies. It covers various aspects of Business from International trade and transactions to Marketing and Communications.</p>

        <p>In my free time I'd like to read, code, cook and spend time with friends and colleagues.</p>
      </div>
    </div>

    <div class="col-sm-3 col-sm-offset-1">
      <img src="/assets/fardin-khanjani.jpg" alt="fardin khanjani" class="profile-pic">
    </div>  
  </div>
</section>

<section id="fun-facts" class="auto-height">
  <div>
    <h1>Some fun facts about me</h1>
    <p>I like my coffee bitter, I'm afraid of height, I cannot decide wheter penguins are my favorite animal or pandas, I am a hardcore 'Friends' fan, foodie, I love airports, I prefer cold weather to hot and I prefer MacBook to PC every time</p>
  </div>

  <%= link_to "Check out my resume", resume_path, class: 'checkout-resume-btn'%>

</section>


<!-- 
  <div class="hr centered" style="margin-bottom: 20px"></div>

  <div class="centered"><%= link_to "Check out my resume", resume_path, class: 'btn a-btn'%></div>
</div>

-->